#!/usr/bin/env python3
"""
n8n Workflow Generator for Movie Notifier
Generates an n8n workflow JSON that replicates the movie-notifier functionality.
"""

# Add parent directory to path for imports
from typing import Dict, List, Any, Optional
from datetime import datetime
import json
from config_manager import ConfigManager
from people_manager import PeopleManager
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class N8NWorkflowGenerator:
    """Generates an n8n workflow JSON for the movie notifier"""

    def __init__(self, config_path: str = "config/config.yaml",
                 people_path: str = "config/people.yaml"):
        """
        Initialize the workflow generator

        Args:
            config_path: Path to configuration file
            people_path: Path to people configuration file
        """
        self.config_manager = ConfigManager(config_path)
        self.people_manager = PeopleManager(people_path)
        self.config = self.config_manager.config_data
        # Load tracked people data
        if not self.people_manager.load_people():
            print("Warning: Could not load people configuration.")

        self.tracked_people = self.people_manager.persons

    def generate_workflow(self) -> Dict[str, Any]:
        """
        Generate the complete n8n workflow JSON

        Returns:
            Dictionary containing the n8n workflow definition
        """
        workflow = {
            "_comment": "This file is auto-generated by scripts/n8n_workflow_generator.py. Do not edit directly.",
            "name": "Movie Notifier",
            "nodes": [],
            "connections": {},
            "settings": {
                "executionOrder": "v1"
            },
            "staticData": None,
            "tags": [],
            "triggerCount": 1,
            "updatedAt": datetime.now().isoformat(),
            "createdAt": datetime.now().isoformat()
        }

        # Get notification config for schedule
        notification_config = self.config_manager.get_notification_config()
        check_interval = "0 0 * * *"  # Default: daily at midnight
        if notification_config and hasattr(notification_config, 'check_interval'):
            check_interval = notification_config.check_interval

        # Parse cron interval for n8n schedule trigger
        schedule_config = self._parse_cron_for_n8n(check_interval)

        # Node 1: Schedule Trigger
        schedule_node = {
            "id": "1",
            "name": "Schedule Trigger",
            "type": "n8n-nodes-base.scheduleTrigger",
            "typeVersion": 1.2,
            "position": [250, 300],
            "parameters": {
                "rule": {
                    "interval": schedule_config
                }
            },
            "webhookId": None
        }
        workflow["nodes"].append(schedule_node)

        # Node 2: Set - Load Tracked People
        set_node = {
            "id": "2",
            "name": "Load Tracked People",
            "type": "n8n-nodes-base.set",
            "typeVersion": 3.3,
            "position": [450, 300],
            "parameters": {
                "mode": "manual",
                "duplicateItem": False,
                "assignments": {
                    "assignments": [
                        {
                            "id": "people",
                            "name": "people",
                            "value": self._get_tracked_people_for_n8n(),
                            "type": "array"
                        }
                    ]
                },
                "includeOtherFields": False,
                "options": {}
            },
            "webhookId": None
        }
        workflow["nodes"].append(set_node)

        # Node 3: Split In Batches - Loop over each person
        split_node = {
            "id": "3",
            "name": "Loop Over Each Person",
            "type": "n8n-nodes-base.splitInBatches",
            "typeVersion": 3,
            "position": [650, 300],
            "parameters": {
                "batchSize": 1,
                "options": {}
            },
            "webhookId": None
        }
        workflow["nodes"].append(split_node)

        # Node 4: HTTP Request - Get Person Combined Credits
        http_node = {
            "id": "4",
            "name": "Get Person Credits",
            "type": "n8n-nodes-base.httpRequest",
            "typeVersion": 4.2,
            "position": [850, 300],
            "parameters": {
                "url": "https://api.themoviedb.org/3/person/{{ $json.people[$context().itemIndex].id }}/combined_credits",
                "method": "GET",
                "sendHeaders": True,
                "headerParameters": {
                    "parameters": [
                        {
                            "name": "Authorization",
                            "value": "Bearer {{ $credentials.tmdbApiKey }}"
                        }
                    ]
                },
                "queryParameters": {
                    "parameters": [
                        {
                            "name": "language",
                            "value": "en-US"
                        }
                    ]
                },
                "options": {
                    "timeout": 30000
                },
                "authentication": "genericCredentialType",
                "genericAuthType": "httpHeaderAuth"
            },
            "webhookId": None,
            "credentials": {
                "httpHeaderAuth": {
                    "id": "",
                    "name": "TMDB API Key"
                }
            }
        }
        workflow["nodes"].append(http_node)

        # Node 5: Function Item - Filter New Releases
        filter_node = {
            "id": "5",
            "name": "Filter New Releases",
            "type": "n8n-nodes-base.functionItem",
            "typeVersion": 1,
            "position": [1050, 300],
            "parameters": {
                "functionCode": self._get_filter_function_code()
            },
            "webhookId": None
        }
        workflow["nodes"].append(filter_node)

        # Node 6: Remove Duplicates
        dedupe_node = {
            "id": "6",
            "name": "Remove Duplicates",
            "type": "n8n-nodes-base.removeDuplicates",
            "typeVersion": 1,
            "position": [1250, 300],
            "parameters": {
                "dupeKey": "id",
                "operation": "removeItemsProcessed"
            },
            "webhookId": None
        }
        workflow["nodes"].append(dedupe_node)

        # Node 7: Send Email
        email_config = self.config_manager.get_email_config()
        send_email_node = {
            "id": "7",
            "name": "Send Email Notification",
            "type": "n8n-nodes-base.sendEmail",
            "typeVersion": 2,
            "position": [1450, 300],
            "parameters": {
                "fromEmail": "{{ $credentials.smtp.fromEmail }}",
                "toEmail": "{{ $credentials.smtp.toEmail }}",
                "subject": "New Movie Releases from Movie Notifier",
                "textFormat": "html",
                "body": self._get_email_body_template(),
                "options": {
                    "fromEmail": "{{ $credentials.smtp.fromEmail }}"
                }
            },
            "webhookId": None,
            "credentials": {
                "smtp": {
                    "id": "",
                    "name": "SMTP Account"
                }
            }
        }
        workflow["nodes"].append(send_email_node)

        # Create connections
        workflow["connections"] = {
            "1": {  # Schedule Trigger
                "main": [
                    [
                        {
                            "node": "2",
                            "type": "main",
                            "index": 0
                        }
                    ]
                ]
            },
            "2": {  # Load Tracked People
                "main": [
                    [
                        {
                            "node": "3",
                            "type": "main",
                            "index": 0
                        }
                    ]
                ]
            },
            "3": {  # Loop Over Each Person
                "main": [
                    [
                        {
                            "node": "4",
                            "type": "main",
                            "index": 0
                        }
                    ]
                ]
            },
            "4": {  # Get Person Credits
                "main": [
                    [
                        {
                            "node": "5",
                            "type": "main",
                            "index": 0
                        }
                    ]
                ]
            },
            "5": {  # Filter New Releases
                "main": [
                    [
                        {
                            "node": "6",
                            "type": "main",
                            "index": 0
                        }
                    ]
                ]
            },
            "6": {  # Remove Duplicates
                "main": [
                    [
                        {
                            "node": "7",
                            "type": "main",
                            "index": 0
                        }
                    ]
                ]
            }
        }

        return workflow

    def _parse_cron_for_n8n(self, cron_expr: str) -> Dict[str, Any]:
        """
        Parse a cron expression for n8n schedule trigger

        Args:
            cron_expr: Cron expression (e.g., "0 0 * * *")

        Returns:
            Dictionary with n8n schedule configuration
        """
        parts = cron_expr.split()

        if len(parts) >= 5:
            # n8n uses: minute, hour, day, month, weekday
            return {
                "type": "cron",
                "expression": f"{parts[0]} {parts[1]} {parts[2]} {parts[3]} {parts[4]}"
            }

        # Default: daily at midnight
        return {
            "type": "cron",
            "expression": "0 0 * * *"
        }

    def _get_tracked_people_for_n8n(self) -> List[Dict[str, Any]]:
        """
        Get tracked people data formatted for n8n

        Returns:
            List of person dictionaries
        """
        people_list = []
        for person in self.tracked_people:
            people_list.append({
                "id": person.id,
                "name": person.name,
                "notify_for": person.notify_for,
                "last_checked": person.last_checked.isoformat() if person.last_checked else ""
            })
        return people_list

    def _get_filter_function_code(self) -> str:
        """
        Get the JavaScript code for filtering new releases

        Returns:
            JavaScript code as string
        """
        return '''// Filter new movie releases from combined credits
const notifyFor = $json.people[$context().itemIndex].notify_for || [];
const lastChecked = $json.people[$context().itemIndex].last_checked || '1970-01-01';
const credits = $json.cast ? $json.cast.concat($json.crew || []) : ($json.crew || []);

// Filter movies only
const movies = credits.filter(c => c.media_type === 'movie' && c.release_date);

// Filter by notify_for roles
const filtered = movies.filter(m => {
    // Check if department/role matches
    const dept = (m.department || '').toLowerCase();
    const job = (m.job || '').toLowerCase();
    
    for (const role of notifyFor) {
        if (dept.includes(role.toLowerCase()) || job.includes(role.toLowerCase())) {
            return true;
        }
    }
    return false;
});

// Filter by release date > last_checked
const newReleases = filtered.filter(m => {
    if (!m.release_date || m.release_date.length < 10) return false;
    return m.release_date >= lastChecked.substring(0, 10);
});

// Add person name to each movie
for (const movie of newReleases) {
    movie.person_name = $json.people[$context().itemIndex].name;
    movie.person_id = $json.people[$context().itemIndex].id;
}

return newReleases;'''

    def _get_email_body_template(self) -> str:
        """
        Get the email body template

        Returns:
            HTML email body template
        """
        return '''<html>
<body>
    <h2>🎬 New Movie Releases</h2>
    <p>New movie releases have been detected for your tracked people.</p>
    
    <h3>New Releases:</h3>
    <ul>
    {{#each $json}}
        <li>
            <strong>{{title}}</strong> ({{release_date}}) - {{character}}
            <br>
            <em>Person: {{person_name}}</em>
        </li>
    {{/each}}
    </ul>
    
    <hr>
    <p style="color: gray; font-size: 12px;">
        Sent by Movie Notifier on {{$now}}
    </p>
</body>
</html>'''

    def save_workflow(self, output_path: str = "n8n/workflow.json") -> bool:
        """
        Save the workflow JSON to a file

        Args:
            output_path: Path to save the workflow JSON

        Returns:
            True if successful, False otherwise
        """
        try:
            workflow = self.generate_workflow()

            # Ensure directory exists
            os.makedirs(os.path.dirname(output_path), exist_ok=True)

            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(workflow, f, indent=2)

            print(f"Workflow saved to: {output_path}")
            return True
        except Exception as e:
            print(f"Error saving workflow: {e}")
            return False

    def import_to_n8n(self, n8n_url: Optional[str] = None, n8n_api_key: Optional[str] = None) -> bool:
        """
        Import the workflow directly to n8n server

        Args:
            n8n_url: URL of the n8n server (defaults to config value)
            n8n_api_key: API key for n8n server (defaults to config value)

        Returns:
            True if successful, False otherwise
        """
        try:
            import requests

            # Use provided values or fall back to config
            url = (n8n_url or
                   (self.config_manager.n8n_config.url if self.config_manager.n8n_config else None) or
                   "http://localhost:5678")
            api_key = n8n_api_key or (
                self.config_manager.n8n_config.api_key if self.config_manager.n8n_config else None)

            if not api_key:
                print("Error: n8n API key is required for direct import.")
                print(
                    "Please set 'n8n.api_key' in config/config.yaml or provide it via arguments.")
                return False

            workflow = self.generate_workflow()
            import_url = f"{url.rstrip('/')}/rest/workflows"
            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}"
            }

            response = requests.post(
                import_url, json=workflow, headers=headers)

            if response.status_code in [200, 201]:
                print(f"Workflow imported successfully to {url}")
                return True
            elif response.status_code == 401:
                print(f"Authentication failed. Please check your n8n API key.")
                return False
            elif response.status_code == 403:
                print(
                    f"Access forbidden. Your API key may not have sufficient permissions.")
                return False
            else:
                print(f"Failed to import workflow: {response.status_code}")
                print(response.text)
                return False
        except ImportError:
            print(
                "requests library not available. Please install it or save the workflow file instead.")
            return False
        except requests.exceptions.ConnectionError:
            print(
                f"Could not connect to n8n server at {url}. Please check the URL and ensure n8n is running.")
            return False
        except requests.exceptions.Timeout:
            print("Connection to n8n server timed out. Please try again.")
            return False
        except Exception as e:
            print(f"Error importing workflow: {e}")
            return False

    def test_connection(self, n8n_url: Optional[str] = None, n8n_api_key: Optional[str] = None) -> bool:
        """
        Test the n8n server connection by creating a simple workflow with a test node
        and verifying it was created.

        Args:
            n8n_url: URL of the n8n server (defaults to config value)
            n8n_api_key: API key for n8n server (defaults to config value)

        Returns:
            True if successful, False otherwise
        """
        try:
            import requests

            # Use provided values or fall back to config
            url = (n8n_url or
                   (self.config_manager.n8n_config.url if self.config_manager.n8n_config else None) or
                   "http://localhost:5678")
            api_key = n8n_api_key or (
                self.config_manager.n8n_config.api_key if self.config_manager.n8n_config else None)

            if not api_key:
                print("Error: n8n API key is required for testing.")
                print(
                    "Please set 'n8n.api_key' in config/config.yaml or provide it via --api-key.")
                return False

            base_url = url.rstrip('/')
            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}"
            }

            # Step 1: Test authentication by checking the current user/me endpoint
            print(f"\n[1/4] Testing authentication with {base_url}...")
            auth_response = requests.get(
                f"{base_url}/rest/users/me", headers=headers, timeout=10)

            if auth_response.status_code == 401:
                print("Authentication failed. Please check your n8n API key.")
                return False
            elif auth_response.status_code == 403:
                print(
                    "Access forbidden. Your API key may not have sufficient permissions.")
                return False
            elif auth_response.status_code != 200:
                print(
                    f"Authentication check failed with status: {auth_response.status_code}")
                return False

            print("   ✓ Authentication successful!")

            # Step 2: Create a simple test workflow with a test node
            print("\n[2/4] Creating test workflow with test node...")
            test_workflow = {
                "name": "Movie Notifier Test Connection",
                "nodes": [
                    {
                        "id": "1",
                        "name": "Test Node",
                        "type": "n8n-nodes-base.set",
                        "typeVersion": 3.3,
                        "position": [250, 300],
                        "parameters": {
                            "mode": "manual",
                            "duplicateItem": False,
                            "assignments": {
                                "assignments": [
                                    {
                                        "id": "test",
                                        "name": "test",
                                        "value": "Connection test successful!",
                                        "type": "string"
                                    }
                                ]
                            },
                            "includeOtherFields": False,
                            "options": {}
                        },
                        "webhookId": None
                    }
                ],
                "connections": {},
                "settings": {
                    "executionOrder": "v1"
                },
                "staticData": None,
                "tags": ["test"],
                "triggerCount": 0,
                "updatedAt": datetime.now().isoformat(),
                "createdAt": datetime.now().isoformat()
            }

            create_response = requests.post(
                f"{base_url}/rest/workflows",
                json=test_workflow,
                headers=headers
            )

            if create_response.status_code not in [200, 201]:
                print(
                    f"Failed to create test workflow: {create_response.status_code}")
                print(create_response.text)
                return False

            created_workflow = create_response.json()
            workflow_id = created_workflow.get("id")
            print(f"   ✓ Test workflow created with ID: {workflow_id}")

            # Step 3: Retrieve the workflow and verify the test node exists
            print("\n[3/4] Verifying workflow and test node...")
            get_response = requests.get(
                f"{base_url}/rest/workflows/{workflow_id}",
                headers=headers
            )

            if get_response.status_code != 200:
                print(
                    f"Failed to retrieve workflow: {get_response.status_code}")
                return False

            retrieved_workflow = get_response.json()

            # Verify workflow name
            workflow_name = retrieved_workflow.get("name", "")
            if "Test Connection" not in workflow_name:
                print(f"Workflow name mismatch: {workflow_name}")
                return False
            print(f"   ✓ Workflow name verified: {workflow_name}")

            # Verify test node exists
            nodes = retrieved_workflow.get("nodes", [])
            test_node_found = False
            for node in nodes:
                if node.get("name") == "Test Node" and node.get("type") == "n8n-nodes-base.set":
                    test_node_found = True
                    break

            if not test_node_found:
                print("Test node not found in workflow!")
                return False
            print("   ✓ Test node verified: 'Test Node' (n8n-nodes-base.set)")

            # Step 4: Clean up - delete the test workflow
            print("\n[4/4] Cleaning up test workflow...")
            delete_response = requests.delete(
                f"{base_url}/rest/workflows/{workflow_id}",
                headers=headers
            )

            if delete_response.status_code in [200, 204]:
                print("   ✓ Test workflow deleted")
            else:
                print(
                    f"   ⚠ Warning: Failed to delete test workflow (status: {delete_response.status_code})")

            print("\n" + "=" * 50)
            print("✓ Connection test PASSED!")
            print("=" * 50)
            print(f"\nSuccessfully verified:")
            print(f"  • n8n server is running at {base_url}")
            print(f"  • Authentication with API key works")
            print(f"  • Can create workflows")
            print(f"  • Can read and verify workflows")
            print(f"  • Can delete workflows")

            return True

        except ImportError:
            print(
                "requests library not available. Please install it: pip install requests")
            return False
        except requests.exceptions.ConnectionError as e:
            print(f"\n✗ Could not connect to n8n server at {url}")
            print("Please ensure:")
            print("  • n8n is running and accessible")
            print("  • The URL is correct")
            return False
        except requests.exceptions.Timeout:
            print("Connection to n8n server timed out. Please try again.")
            return False
        except Exception as e:
            print(f"Error during connection test: {e}")
            return False


def main():
    """Main entry point for the workflow generator"""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate n8n workflow for Movie Notifier")
    parser.add_argument("--config", "-c", default="config/config.yaml",
                        help="Path to configuration file")
    parser.add_argument("--people", "-p", default="config/people.yaml",
                        help="Path to people configuration file")
    parser.add_argument("--output", "-o", default="n8n/workflow.json",
                        help="Output path for workflow JSON")
    parser.add_argument("--import", dest="import_to_server", action="store_true",
                        help="Import workflow directly to n8n server")
    parser.add_argument("--url", default="http://localhost:5678",
                        help="n8n server URL (default: http://localhost:5678)")
    parser.add_argument("--api-key", dest="api_key",
                        help="n8n API key for direct import (or set via config)")
    parser.add_argument("--test", action="store_true",
                        help="Test n8n server connection by creating and verifying a simple workflow")

    args = parser.parse_args()

    generator = N8NWorkflowGenerator(
        config_path=args.config,
        people_path=args.people
    )

    if args.test:
        success = generator.test_connection(args.url, args.api_key)
    elif args.import_to_server:
        success = generator.import_to_n8n(args.url, args.api_key)
    else:
        success = generator.save_workflow(args.output)

    if args.test:
        return 0 if success else 1

    if success:
        print("\n=== Next Steps ===")
        print("1. Import the workflow JSON into n8n")
        print("2. Set up credentials in n8n:")
        print("   - TMDB API Key (Header Auth)")
        print("   - SMTP Account")
        print("3. Enable the workflow")
        return 0
    else:
        return 1


if __name__ == "__main__":
    sys.exit(main())
